// Project inventory preserved from the original portfolio.
    const rawProjects = [
      {
        id: 1,
        title: 'Reload STAG/DEV from PROD',
        year: '2025',
        status: 'Internal Utility',
        systemId: 'core-data',
        systemLabel: 'Core Data Architecture',
        summary: 'Automated environment refresh pipeline that resets staging and development from production-safe snapshots.',
        architecture: 'Designed guarded reset workflows, data scrub sequencing, and repeatable environment provisioning patterns.',
        impact: 'Reduced reset time and prevented stale data drift between environments.',
        stack: 'AWS, DynamoDB, OpenSearch, automation scripting',
        proof: 'Internal utility in active engineering workflow.',
        tags: ['Automation', 'Environment Management', 'AWS'],
        demoUrl: '',
        codeUrl: '',
        image: 'static/project_1_reload_stag_dev.svg'
      },
      {
        id: 2,
        title: 'ImmPort Log System with Retry Controls',
        year: '2025',
        status: 'Pipeline Delivered',
        systemId: 'core-data',
        systemLabel: 'Core Data Architecture',
        summary: 'Resilient logging pipeline using Step Functions retry controls for observable and recoverable ingestion.',
        architecture: 'Specified retry and failure-state transitions for durable pipeline execution and incident traceability.',
        impact: 'Increased fault tolerance and reduced silent pipeline failures during operational load.',
        stack: 'AWS Step Functions, event logging, operational telemetry',
        proof: 'Deployed internally for production support workflows.',
        tags: ['Data Pipelines', 'Reliability', 'Observability'],
        demoUrl: '',
        codeUrl: '',
        image: 'static/immport_log.png'
      },
      {
        id: 3,
        title: 'Getting Started with AI Prototyping',
        year: '2025',
        status: 'Live Demo',
        systemId: 'intelligent-products',
        systemLabel: 'Intelligent Data Products',
        summary: 'Practical AI build system for engineers covering orchestration, vector retrieval, and model integration.',
        architecture: 'Structured reusable prototyping patterns for ingestion, retrieval, and response flows.',
        impact: 'Accelerated onboarding into applied AI/data workflows with repeatable templates.',
        stack: 'LangFlow, ETLLM, vector search, Groq API',
        proof: 'Public live demo available.',
        tags: ['AI Workflows', 'Enablement', 'Knowledge Systems'],
        demoUrl: 'http://difz-ai-info.s3-website-us-east-1.amazonaws.com/',
        codeUrl: '',
        image: 'static/project_3_ai_prototyping.png'
      },
      {
        id: 4,
        title: 'Neo4j Natural Language UI',
        year: '2025',
        status: 'Prototype',
        systemId: 'core-data',
        systemLabel: 'Core Data Architecture',
        summary: 'Natural language access layer for graph data exploration and relationship-centric query workflows.',
        architecture: 'Mapped intent-to-graph-query translation into a usable retrieval interface for non-Cypher users.',
        impact: 'Lowered graph database access friction and improved cross-team data fluency.',
        stack: 'Neo4j, natural language interface, graph visualization',
        proof: 'Prototype demonstrated through internal walkthrough.',
        tags: ['Graph Databases', 'Semantic Query', 'Neo4j'],
        demoUrl: '',
        codeUrl: '',
        image: 'static/project_4_neo4j_nlui.svg'
      },
      {
        id: 5,
        title: 'MySQL Natural Language Query System',
        year: '2025',
        status: 'Prototype',
        systemId: 'core-data',
        systemLabel: 'Core Data Architecture',
        summary: 'NL-to-SQL query layer that translates intent into structured MySQL queries for business users.',
        architecture: 'Defined translation and validation flow between user prompts and executable SQL.',
        impact: 'Enabled faster self-service analytics without requiring direct SQL expertise.',
        stack: 'MySQL, LangChain, NLP parsing',
        proof: 'Prototype available for architecture review.',
        tags: ['SQL Access', 'NLP', 'Data Democratization'],
        demoUrl: '',
        codeUrl: '',
        image: 'static/project_5_mysql_nlq.svg'
      },
      {
        id: 6,
        title: 'Poster Presenter AI Bot',
        year: '2025',
        status: 'Prototype',
        systemId: 'intelligent-products',
        systemLabel: 'Intelligent Data Products',
        summary: 'Multimodal assistant that combines vision, speech, and LLM orchestration for interactive poster sessions.',
        architecture: 'Composed event routing across Rekognition, STT/TTS, and LLM response generation.',
        impact: 'Validated real-time multimodal interaction model for guided knowledge delivery.',
        stack: 'AWS Rekognition, STT/TTS, AI agent orchestration',
        proof: 'Working prototype for demo environments.',
        tags: ['Multimodal AI', 'Agents', 'Realtime'],
        demoUrl: '',
        codeUrl: '',
        image: 'static/project_6_poster_presenter.svg'
      },
      {
        id: 7,
        title: 'ResumeAI - LLM Resume Parser & Matcher',
        year: '2025',
        status: 'In Development',
        systemId: 'intelligent-products',
        systemLabel: 'Intelligent Data Products',
        summary: 'Resume extraction and matching workflow that structures unformatted candidate data for proposal alignment.',
        architecture: 'Built normalization pipeline from document parsing to criteria-based matching outputs.',
        impact: 'Reduced manual transformation effort in staffing and proposal workflows.',
        stack: 'LLM pipelines, extraction logic, matching heuristics',
        proof: 'Login-protected live demo available.',
        tags: ['Data Normalization', 'LLM', 'Workflow Automation'],
        demoUrl: 'https://resume-ai-sigma-eight.vercel.app/',
        codeUrl: '',
        image: 'static/project_7_resumeai.png'
      },
      {
        id: 8,
        title: 'Data Engineer Skills Assessment',
        year: '2026',
        status: 'Live Demo',
        systemId: 'core-data',
        systemLabel: 'Core Data Architecture',
        summary: 'Interactive assessment platform that demonstrates applied data engineering capability through realistic workflows.',
        architecture: 'Designed scenario-based checkpoints around modeling, pipeline logic, orchestration, and troubleshooting.',
        impact: 'Creates concrete proof of data engineering depth for hiring and stakeholder evaluation.',
        stack: 'Interactive web application, data workflow simulation, competency scoring',
        proof: 'Public live demo available.',
        tags: ['Data Engineering', 'Assessment', 'Applied Skills'],
        demoUrl: 'https://dwba3xr50k6pd.cloudfront.net/',
        codeUrl: '',
        image: 'static/project_8_data_engineer_assessment.png'
      },
      {
        id: 9,
        title: 'Aerospace Orbital Command',
        year: '2026',
        status: 'Live Demo',
        systemId: 'interface-labs',
        systemLabel: 'Applied Product Interfaces',
        summary: 'Telemetry-rich orbital interface for tracking movement, state, and mission context in real time.',
        architecture: 'Applied data-to-visual mapping patterns for high-signal command surfaces.',
        impact: 'Demonstrates translating complex streams into understandable control interfaces.',
        stack: 'Realtime visualization, map overlays, frontend telemetry UX',
        proof: 'Public live demo available.',
        tags: ['Visualization', 'Telemetry', 'Interaction Design'],
        demoUrl: 'https://isstracker-nine.vercel.app/',
        codeUrl: '',
        image: 'static/project_9_aerospace_orbital_command.png'
      },
      {
        id: 10,
        title: 'Vibe Coding Journey',
        year: '2026',
        status: 'Live Demo',
        systemId: 'interface-labs',
        systemLabel: 'Applied Product Interfaces',
        summary: 'Guided learning product that sequences concept delivery with progressive interactive checkpoints.',
        architecture: 'Structured instructional flow and state progression for high-completion onboarding.',
        impact: 'Improved knowledge transfer through measurable, staged interaction design.',
        stack: 'Frontend application, educational UX, progressive interaction',
        proof: 'Public live demo available.',
        tags: ['Learning Systems', 'Product UX', 'Frontend'],
        demoUrl: 'https://vibe-journey-xi.vercel.app/',
        codeUrl: '',
        image: 'static/project_10_vibe_coding_journey.png'
      },
      {
        id: 11,
        title: 'ClawdMarks',
        year: '2026',
        status: 'Live Site',
        systemId: 'intelligent-products',
        systemLabel: 'Intelligent Data Products',
        summary: 'Operational intelligence workspace for monitoring and coordinating AI-assisted execution at scale.',
        architecture: 'Established data surfaces for agent-state visibility, workflow control, and reliability inspection.',
        impact: 'Improved operational clarity in AI-heavy delivery environments.',
        stack: 'AI operations UX, execution telemetry, coordination layer',
        proof: 'Public site available.',
        tags: ['AI Operations', 'Control Plane', 'Operational Intelligence'],
        demoUrl: 'https://www.clawdmarks.com/',
        codeUrl: '',
        image: 'static/project_11_clawdmarks.png'
      },
      {
        id: 12,
        title: 'Mission Control',
        year: '2026',
        status: 'Live Demo',
        systemId: 'core-data',
        systemLabel: 'Core Data Architecture',
        summary: 'Mission-style control interface for orchestrating system operations with status-aware dashboards.',
        architecture: 'Consolidated multi-source operational data into a single command and response surface.',
        impact: 'Reduced context switching and improved response speed during operations.',
        stack: 'Dashboard architecture, orchestration UX, operational status tracking',
        proof: 'Public live demo available.',
        tags: ['Command Interface', 'Operations', 'Monitoring'],
        demoUrl: 'https://d2vkpyz88pgyjq.cloudfront.net/',
        codeUrl: '',
        image: 'static/project_12_mission_control.png'
      },
      {
        id: 13,
        title: 'Vanessa Markowitz',
        year: '2026',
        status: 'Live Site',
        systemId: 'interface-labs',
        systemLabel: 'Applied Product Interfaces',
        summary: 'Narrative-first web presence engineered for clarity, credibility, and audience conversion.',
        architecture: 'Designed content architecture and responsive structure for clean information hierarchy.',
        impact: 'Delivered polished external communication platform with strong readability.',
        stack: 'Frontend architecture, branding UX, content systems',
        proof: 'Public site available.',
        tags: ['Website Architecture', 'Storytelling', 'UX'],
        demoUrl: 'https://www.vanessamarkowitz.com/',
        codeUrl: '',
        image: 'static/project_13_vanessa_markowitz.png'
      },
      {
        id: 14,
        title: 'DMBMarko Studio Album Experience',
        year: '2026',
        status: 'Live Demo',
        systemId: 'interface-labs',
        systemLabel: 'Applied Product Interfaces',
        summary: 'Media-rich interactive album system with track sequencing, lyrics, and cinematic transitions.',
        architecture: 'Engineered interaction choreography and playback-centric state handling.',
        impact: 'Showcases strong frontend systems thinking in a creative product environment.',
        stack: 'Interactive media UI, audio UX, motion-led frontend',
        proof: 'Public live demo available.',
        tags: ['Creative Systems', 'Audio UX', 'Interaction'],
        demoUrl: 'https://dmbrian.vercel.app/',
        codeUrl: '',
        image: 'static/project_14_dmbrian.png'
      },
{
    id: 15,
    title: 'Clawbot Patch Blog',
    year: '2026',
    status: 'Live Blog',
    systemId: 'intelligent-products',
    systemLabel: 'Intelligent Data Products',
    summary: 'Operational patch log documenting AI workflow behavior, fixes, and reliability improvements.',
    architecture: 'Created engineering knowledge stream for change transparency and operational learning loops.',
    impact: 'Captured repeatable lessons and reduced ambiguity in AI-assistant operations.',
    stack: 'Documentation pipeline, AI operations reporting, public engineering notes',
    proof: 'Public blog available.',
    tags: ['Knowledge Ops', 'AI Reliability', 'Engineering Notes'],
    demoUrl: 'https://brianmarkowitz.github.io/patch-blog/',
    codeUrl: '',
    image: 'static/project_15_patch_blog.png'
  },
  {
    id: 16,
    title: 'Brian Resume',
    year: '2026',
    status: 'Live Site',
    systemId: 'interface-labs',
    systemLabel: 'Applied Product Interfaces',
    summary: 'Professional resume showcase with clean, modern design optimized for readability and impact.',
    architecture: 'Designed structured content presentation with responsive layout and clear information hierarchy.',
    impact: 'Delivers professional first impression with accessible, well-organized career narrative.',
    stack: 'Frontend architecture, responsive design, content systems',
    proof: 'Public site available.',
    tags: ['Resume', 'Personal Branding', 'UX'],
    demoUrl: 'https://brianresume.vercel.app/',
    codeUrl: '',
    image: 'static/project_16_brian_resume.png'
  },
  {
    id: 17,
    title: 'ResumeDB',
    year: '2026',
    status: 'Live Site',
    systemId: 'intelligent-products',
    systemLabel: 'Intelligent Data Products',
    summary: 'Resume database platform for managing and showcasing professional profiles at scale.',
    architecture: 'Built data-driven resume storage and retrieval system with searchable profile interfaces.',
    impact: 'Streamlines resume management and discovery for recruitment and professional networking workflows.',
    stack: 'Data storage, search interfaces, profile management',
    proof: 'Public site available.',
    tags: ['Data Products', 'Search', 'Profile Management'],
    demoUrl: 'https://resumedb.vercel.app/',
    codeUrl: '',
    image: 'static/project_17_resumedb.png'
  },
  {
    id: 18,
    title: 'FluGlobe Visualization',
    year: '2026',
    status: 'Live Demo',
    systemId: 'interface-labs',
    systemLabel: 'Applied Product Interfaces',
    summary: 'Interactive globe visualization for tracking global avian influenza outbreaks and migratory flyway patterns.',
    architecture: 'Combined geospatial rendering, filter controls, and timeline slicing into a single exploratory monitoring interface.',
    impact: 'Transforms multi-source outbreak signals into an understandable situational awareness experience for rapid analysis.',
    stack: '3D globe visualization, geospatial UI, filter-driven interaction',
    proof: 'Public live demo available.',
    tags: ['Geospatial Visualization', 'Public Health Data', 'Interactive UI'],
    demoUrl: 'https://fluglobe.vercel.app/',
    codeUrl: '',
    image: 'static/project_18_fluglobe.png'
  },
  {
    id: 19,
    title: 'Prompt Library',
    year: '2026',
    status: 'Live Demo',
    systemId: 'intelligent-products',
    systemLabel: 'Intelligent Data Products',
    summary: 'Local-first prompt management app for organizing reusable AI prompts, categories, search, and quick-copy workflows.',
    architecture: 'Built a browser-native library surface with prompt metadata, category organization, variable-aware templates, and persistent local storage.',
    impact: 'Reduces repeated prompt drafting and gives teams a structured workspace for reusable AI operating patterns.',
    stack: 'React, local storage, prompt templating, responsive product UX',
    proof: 'Public live demo available.',
    tags: ['Prompt Engineering', 'Knowledge Systems', 'AI Enablement'],
    demoUrl: 'https://prompt-library-ten-lac.vercel.app/',
    codeUrl: '',
    image: 'static/project_19_prompt_library.png'
  },
  {
    id: 20,
    title: 'Compliance Tracker Workspace',
    year: '2026',
    status: 'Live Demo',
    systemId: 'interface-labs',
    systemLabel: 'Applied Product Interfaces',
    summary: 'Acquisition request workspace for intake, checklist readiness, status routing, and manager/specialist review.',
    architecture: 'Separated requester, manager, and specialist workspaces with role-aware queues, readiness scoring, and request detail workflows.',
    impact: 'Turns acquisition support into a visible queue with actionable status, blockers, and next-step controls.',
    stack: 'React, role-based workflow UX, request queue modeling, compliance operations',
    proof: 'Public live demo available.',
    tags: ['Workflow Systems', 'Compliance', 'Operations UX'],
    demoUrl: 'https://acquisitions-tracker.vercel.app/',
    codeUrl: '',
    image: 'static/project_20_acquisitions_tracker.png'
  },
  {
    id: 21,
    title: 'ImmPort Intervention/Cohort Export',
    year: '2026',
    status: 'Protected Console',
    systemId: 'core-data',
    systemLabel: 'Core Data Architecture',
    summary: 'QC operator console for running approved ImmPort intervention and cohort exports, managing the study library, and downloading generated ZIP packages.',
    architecture: 'Composed protected operator workflows for study selection, readiness checks, export execution, activity tracking, admin accounts, and audit diagnostics.',
    impact: 'Gives operators a governed export surface with repeatable run history, readiness gates, and package downloads.',
    stack: 'AWS, Cognito, export orchestration, operator console, ZIP packaging',
    proof: 'Login-protected production console available.',
    tags: ['ImmPort', 'CIVICs', 'Export Operations'],
    demoUrl: 'https://immport-cohort-export-prod.sdmcc.niaidcivics.org/',
    codeUrl: '',
    image: 'static/project_21_immport_cohort_export.png'
  },
  {
    id: 22,
    title: 'Agent Skills Library',
    year: '2026',
    status: 'Live Workspace',
    systemId: 'intelligent-products',
    systemLabel: 'Intelligent Data Products',
    summary: 'Governed agent skills catalog and request workspace for shared workflows, install guidance, access roles, and operational analytics.',
    architecture: 'Combined public inventory/docs with signed-in install requests, governance review, reports, analytics, and admin access controls.',
    impact: 'Standardizes reusable agent workflows with a governed path from request to validation to install.',
    stack: 'AWS Cognito, inventory generation, governance workflow, analytics dashboard',
    proof: 'Public catalog and live workspace available.',
    tags: ['Agent Workflows', 'Governance', 'Knowledge Systems'],
    demoUrl: 'https://skills.idpcc.ceirr-network-dev.org/',
    backupUrl: 'https://agent-skills-backup.vercel.app/',
    backupLabel: 'Open Backup',
    codeUrl: '',
    image: 'static/project_22_agent_skills_library.png'
  },
  {
    id: 23,
    title: 'iDPCC Export Dashboard',
    year: '2026',
    status: 'Protected Console',
    systemId: 'core-data',
    systemLabel: 'Core Data Architecture',
    summary: 'BV-BRC package operations dashboard for searching export-ready records, previewing impact, and generating governed CSV packages.',
    architecture: 'Built filter-driven export source selection, dry-run side-effect review, package history, and returned BV-BRC accession ID update workflows.',
    impact: 'Provides governed export packaging and accession reconciliation for BV-BRC submission operations.',
    stack: 'React, AWS Cognito, governed CSV exports, operational run history',
    proof: 'Login-protected production dashboard available.',
    tags: ['BV-BRC', 'iDPCC', 'Export Operations'],
    demoUrl: 'https://bvbrc-export.idpcc.ceirr-network.org/',
    codeUrl: '',
    image: 'static/project_23_bvbrc_export_dashboard.png'
  },
  {
    id: 24,
    title: 'HRSA Contract Closeout Assistant',
    year: '2026',
    status: 'Live Demo',
    systemId: 'core-data',
    systemLabel: 'Core Data Architecture',
    summary: 'Contract closeout workbench for triaging HRSA closeout files, readiness gaps, stakeholder requests, and contracting officer review.',
    architecture: 'Modeled role-aware queues, checklist readiness, deobligation signals, stakeholder follow-up, evidence review, and advisory closeout guidance.',
    impact: 'Turns fragmented contract closeout status into a clear operator workspace with next actions, aging signals, and accountable review paths.',
    stack: 'React, Vercel, contract closeout workflow UX, advisory rules, operator dashboards',
    proof: 'Public live demo available.',
    tags: ['Contract Closeout', 'HRSA', 'Workflow Systems'],
    demoUrl: 'https://hrsa-closeout-codex-prototype.vercel.app/',
    codeUrl: '',
    image: 'static/project_24_hrsa_closeout.png'
  },
  {
    id: 25,
    title: 'D-TAIP Prototype',
    year: '2026',
    status: 'Live Demo',
    systemId: 'intelligent-products',
    systemLabel: 'Intelligent Data Products',
    summary: 'Deflection technical assistance workspace that structures raw workshop notes into DSAP-aligned action plans.',
    architecture: 'Combined synthetic workshop scenarios, DSAP coverage checks, AI-assisted drafting, facilitator decisions, and reusable method memory.',
    impact: 'Helps facilitators convert messy planning sessions into structured action-plan language while keeping final decisions human-owned.',
    stack: 'React, Vercel, Groq AI, DSAP workflow modeling, knowledge graph memory',
    proof: 'Public live demo available.',
    tags: ['Technical Assistance', 'AI Facilitation', 'Action Planning'],
    demoUrl: 'https://d-taip-prototype.vercel.app/',
    codeUrl: '',
    image: 'static/project_25_d_taip.png'
  },
  {
    id: 26,
    title: 'Brian Wiki',
    year: '2026',
    status: 'Protected Site',
    systemId: 'intelligent-products',
    systemLabel: 'Intelligent Data Products',
    summary: 'Protected personal Memory Wiki for browsing imported Codex history through daily logs, search, graph navigation, and mode-aware themes.',
    architecture: 'Built hash-routed private wiki access, local memory import surfaces, date-based navigation, search affordances, and Work/LCARS theme modes.',
    impact: 'Creates a durable recall layer for prior agent work while keeping the archive behind explicit access controls.',
    stack: 'Static React app, generated memory data, protected access, hash routing, themed UI modes',
    proof: 'PIN-protected private workspace available.',
    tags: ['Memory Wiki', 'Knowledge Systems', 'Private Workspace'],
    demoUrl: 'https://brian-wiki.vercel.app/#/log/2026-05-24',
    codeUrl: '',
    image: 'static/project_26_brian_wiki_lcars.png',
    galleryLabels: ['LCARS Mode', 'Work Mode', 'LCARS Mode', 'Work Mode']
  }
];

    const impressivenessOrder = [24, 25, 23, 21, 8, 22, 26, 20, 2, 4, 5, 11, 19, 18, 10, 1, 12, 3, 7, 15, 16, 17, 6, 9, 13, 14];
    const rankById = Object.fromEntries(impressivenessOrder.map((id, index) => [id, index + 1]));

    const galleryExtrasById = {
      3: [
        'static/project_3_ai_prototyping_extra_1.png',
        'static/project_3_ai_prototyping_extra_2.png',
        'static/project_3_ai_prototyping_extra_3.png'
      ],
      7: [
        'static/project_7_resumeai_extra_1.png',
        'static/project_7_resumeai_extra_2.png',
        'static/project_7_resumeai_extra_3.png'
      ],
      8: [
        'static/project_8_data_engineer_assessment_extra_1.png',
        'static/project_8_data_engineer_assessment_extra_2.png',
        'static/project_8_data_engineer_assessment_extra_3.png'
      ],
      9: [
        'static/project_9_aerospace_orbital_command_extra_1.png',
        'static/project_9_aerospace_orbital_command_extra_2.png',
        'static/project_9_aerospace_orbital_command_extra_3.png'
      ],
      10: [
        'static/project_10_vibe_coding_journey_extra_1.png',
        'static/project_10_vibe_coding_journey_extra_2.png',
        'static/project_10_vibe_coding_journey_extra_3.png'
      ],
      11: [
        'static/project_11_clawdmarks_extra_1.png',
        'static/project_11_clawdmarks_extra_2.png',
        'static/project_11_clawdmarks_extra_3.png'
      ],
      12: [
        'static/project_12_mission_control_extra_1.png',
        'static/project_12_mission_control_extra_2.png',
        'static/project_12_mission_control_extra_3.png'
      ],
      13: [
        'static/project_13_vanessa_markowitz_extra_1.png',
        'static/project_13_vanessa_markowitz_extra_2.png',
        'static/project_13_vanessa_markowitz_extra_3.png'
      ],
      14: [
        'static/project_14_dmbrian_extra_1.png',
        'static/project_14_dmbrian_extra_2.png',
        'static/project_14_dmbrian_extra_3.png'
      ],
      15: [
        'static/project_15_patch_blog_extra_1.png',
        'static/project_15_patch_blog_extra_2.png',
        'static/project_15_patch_blog_extra_3.png'
      ],
      16: [
        'static/project_16_brian_resume_extra_1.png',
        'static/project_16_brian_resume_extra_2.png',
        'static/project_16_brian_resume_extra_3.png'
      ],
      17: [
        'static/project_17_resumedb_extra_1.png',
        'static/project_17_resumedb_extra_2.png',
        'static/project_17_resumedb_extra_3.png'
      ],
      18: [
        'static/project_18_fluglobe_extra_1.png',
        'static/project_18_fluglobe_extra_2.png',
        'static/project_18_fluglobe_extra_3.png'
      ],
      26: [
        'static/project_26_brian_wiki_work.png',
        'static/project_26_brian_wiki_lcars.png',
        'static/project_26_brian_wiki_work.png'
      ]
    };
